"""empty message

Revision ID: 10a5cb666d12
Revises: 5f41bc135010
Create Date: 2019-07-22 10:54:09.036523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a5cb666d12'
down_revision = '5f41bc135010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('date_create', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'date_create')
    # ### end Alembic commands ###
