"""empty message

Revision ID: 7fa1ba2215cb
Revises: 10a5cb666d12
Create Date: 2019-07-22 14:33:42.013834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa1ba2215cb'
down_revision = '10a5cb666d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'pick_date',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('booking', 'return_date',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'return_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('booking', 'pick_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
