"""empty message

Revision ID: c10398197213
Revises: 52801ce2d1b7
Create Date: 2019-07-16 11:27:54.223524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10398197213'
down_revision = '52801ce2d1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_bill', sa.String(length=255), nullable=False),
    sa.Column('date_create', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('gear_box', sa.String(length=255), nullable=False),
    sa.Column('door', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=999), nullable=False),
    sa.Column('price', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('pick_date', sa.String(length=255), nullable=False),
    sa.Column('return_date', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('firstname', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('lastname', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=False))
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'email')
    op.drop_table('booking')
    op.drop_table('car')
    op.drop_table('billing')
    # ### end Alembic commands ###
