"""empty message

Revision ID: f34030dc7a29
Revises: f81a9c631c2c
Create Date: 2019-07-16 16:45:22.872545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34030dc7a29'
down_revision = 'f81a9c631c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('img', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'img')
    # ### end Alembic commands ###
